# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: andretai-sandbox/gh-actions-test-target
          path: './gh-actions-test-target'
          token: ${{ secrets.PAT }}
      - name: Set up git config
        run: |
          pwd
          ls
          cd gh-actions-test-target
          pwd
      - name: Check if file exists, create if not
        run: |
          pwd

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      # Runs a set of commands using the runners shell
#       - name: Verify configuration
#         run: |
#           pwd
#           whoami
#           git --version
#           git config --global user.email "andretai.wx@gmail.com"
#           git config --global user.name "Andre Tai"
#           git config -l
#       - name: Clone target repository
#         run: |
#           git clone https://github.com/andretai-sandbox/gh-actions-test-target.git
#       - name: Create or update file
#         run: |
#           cd gh-actions-test-target
#           pwd
#           git remote set-url origin https://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:andretai@github.com/andretai-sandbox/gh-actions-test-target.git
#           touch new_file.txt
#           echo "this is a new file" > new_file.txt
#           git add new_file.txt
#           git commit -m "Create new_file.txt"
#           git push
          
